name: Deploy React to Pi

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # use your node version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy files to Pi
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: 2222
          source: "build/*"
          target: "/var/www/domain.nl/"

      - name: Restart Nginx (optional)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: 2222
          script: sudo systemctl reload nginx
